<a href="https://colab.research.google.com/github/KULDEEPSONI-source/MACHINE-LEARNING/blob/main/ENSEMBLE-BOOSTING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.metrics import accuracy_score

In [56]:
df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [57]:
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [59]:
df.TotalCharges = pd.to_numeric(df.TotalCharges, errors='coerce')

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [61]:
df.dropna(how='any', inplace=True)

In [62]:
len(df)

7032

In [63]:
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [64]:
df.Churn.value_counts()/len(df)*100

Churn
No     73.421502
Yes    26.578498
Name: count, dtype: float64

In [65]:
X=df.drop(['customerID', 'Churn'], axis=1)

In [66]:
y=df.Churn.values

In [67]:
X

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50

In [68]:
y

array(['No', 'No', 'Yes', ..., 'No', 'Yes', 'No'], dtype=object)

In [69]:
X.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='object')

In [70]:
# Convert categorical features to numericals --> Feature Encoding --> Dummy Encoding

X = pd.get_dummies(X, columns=['gender', 'Partner', 'Dependents',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod'], drop_first=True)

In [71]:
X.head(1)

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,False,True,False,False,True,False,...,False,False,False,False,False,False,True,False,True,False

In [72]:
# Splitting the data into training & test

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25)

In [73]:
len(X_train)

5274

In [74]:
len(X_test)

1758

In [75]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [76]:
X_train_sc

array([[-0.43986667,  0.97914485, -1.29546772, ..., -0.51983768,
        -0.71496488, -0.54974742],
       [-0.43986667, -1.2249236 ,  0.53567285, ..., -0.51983768,
         1.39867009, -0.54974742],
       [-0.43986667, -1.26573968,  1.21818888, ..., -0.51983768,
         1.39867009, -0.54974742],
       ...,
       [-0.43986667,  0.77506443, -0.15683122, ..., -0.51983768,
        -0.71496488, -0.54974742],
       [-0.43986667, -0.36778587,  0.73043962, ..., -0.51983768,
        -0.71496488,  1.81901719],
       [-0.43986667, -0.81676278,  0.39084628, ..., -0.51983768,
         1.39867009, -0.54974742]])

In [77]:
X_test_sc

array([[-0.43986667, -1.2249236 ,  0.57063099, ..., -0.51983768,
         1.39867009, -0.54974742],
       [-0.43986667,  0.36690361,  0.82199665, ..., -0.51983768,
         1.39867009, -0.54974742],
       [-0.43986667,  0.1628232 , -0.39155015, ..., -0.51983768,
        -0.71496488,  1.81901719],
       ...,
       [-0.43986667,  1.3056735 ,  1.51949474, ...,  1.92367741,
        -0.71496488, -0.54974742],
       [-0.43986667, -1.10247535, -0.46146643, ..., -0.51983768,
        -0.71496488,  1.81901719],
       [-0.43986667, -0.24533762, -0.34327462, ...,  1.92367741,
        -0.71496488, -0.54974742]])

### **Ensemble Learning**

#### **Adaboost**

---
AdaBoost, or **Adaptive Boosting**, is a powerful ensemble machine learning algorithm that transforms a collection of "weak learners"—models that perform only slightly better than random guessing—into a single, high-performance "strong learner."

Unlike methods like Random Forest that train models independently in parallel, AdaBoost builds models **sequentially**, with each new model specifically designed to correct the errors of its predecessor.

---

### The Core Mechanics (Step-by-Step)

The "adaptive" nature of the algorithm refers to how it adjusts the importance of training data at each stage.

1. **Initialize Weights:** Every data point in your training set is assigned an equal initial weight, $w_i = 1/N$, where $N$ is the total number of samples.
2. **Train Weak Learner:** A base model (commonly a "decision stump," which is a one-level decision tree) is trained on the data.
3. **Calculate Error Rate ($\epsilon$):** The algorithm calculates the total error for the current model. This is the sum of the weights of all misclassified points.
4. **Determine "Amount of Say" ($\alpha$):** A weight ($\alpha$) is calculated for the learner based on its error rate:

$$\alpha = \frac{1}{2} \ln \left( \frac{1 - \epsilon}{\epsilon} \right)$$


* If a learner has a low error, it receives a **high $\alpha$** (it gets more "say" in the final vote).
* If the error is 0.5 (random guessing), the learner receives zero "say."


5. **Update Data Weights:** The weights of the misclassified data points are increased, while the weights of correctly classified points are decreased. This forces the *next* weak learner to focus specifically on the "hard" examples.
6. **Normalize:** The new weights are normalized so they sum to 1.
7. **Repeat:** Steps 2–6 are repeated for a predefined number of iterations.
8. **Final Prediction:** The final output is the **weighted sign sum** of all the weak learners:

$$H(x) = \text{sign} \left( \sum_{t=1}^T \alpha_t h_t(x) \right)$$



---

### Strengths and Weaknesses

| **Pros** | **Cons** |
| --- | --- |
| **High Accuracy:** Often produces excellent predictive power for classification tasks. | **Sensitivity to Outliers:** Since it "pushes" to fix errors, noisy data or extreme outliers can cause the model to overfit. |
| **Versatility:** Can be paired with almost any machine learning algorithm as its "base" learner. | **Computationally Intensive:** Because it is a sequential process, it can be slower to train on very large datasets compared to parallel methods. |
| **Easy to Configure:** Often works well without extensive parameter tuning (out-of-the-box performance). | **Risk of Over-specialization:** Over-emphasizing hard-to-classify points can sometimes lead the model to lose focus on the overall pattern. |

---

### When to Use It

AdaBoost is particularly effective in scenarios where you have a complex classification problem and need a model that can capture subtle patterns. It has historically been a foundational technique in fields like **object detection** (e.g., face detection systems).

[View a step-by-step AdaBoost numerical example](https://www.youtube.com/watch?v=l3DzJBb3MaE)

This video provides a practical, walkthrough-style example that helps visualize the manual calculation of weights and the "Amount of Say" (Alpha) for a small dataset, which is helpful for reinforcing the mathematical concepts discussed.
---

In [78]:
# Call the AdaBoost Classifier
from sklearn.ensemble import AdaBoostClassifier

# Initiating the classifier
model_ada = AdaBoostClassifier(n_estimators=200)

# Passing the data to classifier
model_ada.fit(X_train_sc, y_train)

# Predictions
y_pred_ada = model_ada.predict(X_test_sc)

print("Accuracy of AdaBoost: ", accuracy_score(y_test, y_pred_ada))

Accuracy of AdaBoost:  0.8094425483503982

#### **Gradient Boost**

---
**Gradient Boosting** is an ensemble machine learning technique that builds a strong predictive model by combining multiple "weak learners"—most commonly shallow decision trees—in a sequential, additive manner.

The core idea is to train each new model to predict the **errors** (residuals) of the entire ensemble created up to that point. By doing this iteratively, the algorithm "boosts" the performance of the model, slowly shrinking the error toward zero.

---

### How It Works: The Iterative Process

Gradient Boosting is often described as "functional gradient descent." Instead of adjusting weights of data points (like AdaBoost), it adjusts the *predictions* themselves to follow the negative gradient of a loss function.

1. **Initial Prediction:** The process starts with a simple, naive model—usually just the mean of the target values (for regression). This is your initial "guess" ($F_0$).
2. **Calculate Residuals:** You calculate the difference between the actual target values and your current prediction. These differences are the "residuals" (the errors).
3. **Train a Weak Learner:** A new decision tree is trained to predict these residuals, *not* the original target values.
4. **Scale and Add:** The new tree’s predictions are multiplied by a **learning rate** (a small value between 0 and 1) to prevent the model from overfitting. This result is added to the previous model’s predictions to create an updated, more accurate model.
5. **Repeat:** You repeat steps 2–4 for a fixed number of iterations ($M$). Each new tree focuses on the patterns in the residuals that the previous trees failed to capture.

---

### Mathematical Intuition

Gradient Boosting is fundamentally about minimizing a **loss function** $L(y, F(x))$.

* **The Residuals as Gradients:** In the simplest case (using Mean Squared Error), the "residual" is exactly the negative gradient of the loss function.
* **Gradient Descent:** By training a new tree to predict the residual, you are essentially taking a "step" in the direction of the steepest descent of the loss function. You aren't just fitting a curve; you are navigating the landscape of the loss function to reach its minimum.

---

### Gradient Boosting vs. AdaBoost

While both are boosting algorithms, they differ in their approach:

| Feature | AdaBoost | Gradient Boosting |
| --- | --- | --- |
| **Primary Method** | Adjusts **weights of data points** to focus on hard-to-classify samples. | Fits new trees to the **residuals** (errors) of previous trees. |
| **Approach** | Adaptive re-weighting. | Gradient descent optimization. |
| **Flexibility** | Can be less robust to noisy data/outliers. | Highly flexible; can optimize any differentiable loss function. |
| **Complexity** | Simple, but can be limited by its rigid focus on errors. | More complex, but often achieves higher accuracy on tabular data. |

---

### Key Components

* **Loss Function:** Defines what "error" means (e.g., Mean Squared Error for regression, Log-Loss for classification).
* **Weak Learners:** Usually decision trees. Unlike AdaBoost (which uses "stumps"), Gradient Boosting trees are often slightly deeper (8–32 nodes) to capture more complex patterns.
* **Learning Rate (Shrinkage):** A hyperparameter that scales the contribution of each tree. A lower learning rate usually results in better generalization but requires more trees to converge.

### Popular Implementations

Because the raw algorithm can be slow, high-performance libraries have been developed that optimize the training process:

* **XGBoost (eXtreme Gradient Boosting):** Known for speed and performance; includes features like parallel processing and regularization to prevent overfitting.
* **LightGBM:** Designed for efficiency and lower memory usage, especially on very large datasets.
* **CatBoost:** Specifically optimized to handle categorical features automatically without requiring extensive pre-processing.

---

---

In [79]:
# Call the GB Classifier
from sklearn.ensemble import GradientBoostingClassifier

# Initiating the classifier
model_gb = GradientBoostingClassifier(n_estimators=200)

# Passing the data to classifier
model_gb.fit(X_train_sc, y_train)

# Predictions
y_pred_gb = model_gb.predict(X_test_sc)

print("Accuracy of GB: ", accuracy_score(y_test, y_pred_gb))

Accuracy of GB:  0.8037542662116041

#### **XG Boost**

---
**XGBoost** (short for **eXtreme Gradient Boosting**) is a highly optimized, open-source implementation of the gradient boosting framework. It is widely considered the "gold standard" for structured (tabular) data in machine learning and is the engine behind many winning solutions in competitive data science (such as on Kaggle).

---

### What is XGBoost?

At its core, XGBoost is a supervised learning algorithm that builds a collection of decision trees sequentially. While standard Gradient Boosting machines (GBM) build trees one after another, XGBoost introduces engineering innovations that make it significantly **faster**, more **efficient**, and less prone to **overfitting**.

---

### How It Works: The "Extreme" Enhancements

XGBoost follows the gradient boosting logic—where each new tree predicts the errors (residuals) of the previous trees—but it improves upon the process in several critical ways:

1. **Regularization:** Unlike basic GBMs, XGBoost includes built-in **L1 (Lasso)** and **L2 (Ridge)** regularization. This penalizes overly complex models (e.g., trees with too many leaves or large weights), forcing the model to remain simpler and preventing it from overfitting to noise in the training data.
2. **Parallelization:** While boosting is inherently sequential, XGBoost parallelizes the process of building a single tree. During the "split-finding" stage, it sorts features in parallel across multiple CPU cores, drastically reducing training time.
3. **Sparsity-Aware Split Finding:** Real-world data is often "sparse" (contains many missing values or zeros). XGBoost automatically learns the "default direction" for missing data at each node, meaning you don't have to spend as much time on manual data imputation.
4. **Cache-Aware Access:** It is designed to be hardware-efficient. It uses internal buffers to store gradient statistics, which optimizes how the CPU fetches data from memory, making the algorithm incredibly fast for large datasets.
5. **Weighted Quantile Sketch:** Instead of scanning every single value when trying to find the best split point, it uses a smart algorithm to estimate the distribution of the data, allowing it to find optimal splits much faster without losing accuracy.

---

### XGBoost vs. Others: Why use it?

| Feature | AdaBoost | Gradient Boosting (GBM) | **XGBoost** |
| --- | --- | --- | --- |
| **Optimization** | Adjusts sample weights | Gradient Descent | Gradient Descent + Regularization |
| **Speed** | Slow (sequential) | Moderate/Slow | **Extremely Fast** |
| **Overfitting** | Prone to noise/outliers | Can overfit easily | **Resistant (via Regularization)** |
| **Missing Data** | Requires imputation | Requires imputation | **Handles automatically** |

---

### Key Strengths

* **Performance:** Consistently delivers top-tier accuracy on tabular data.
* **Scalability:** Can handle massive datasets that don't fit into memory (out-of-core computing).
* **Flexibility:** Allows you to define custom loss functions, making it useful for a wide range of tasks (classification, regression, ranking).
* **Production-Ready:** Includes features like early stopping (to stop training when performance plateaus) and cross-validation, which are essential for real-world deployments.

### Summary

Think of **AdaBoost** as a group of people voting where some have more "authority" than others. Think of **Gradient Boosting** as a student learning from their mistakes by calculating exactly how far off their last answer was. **XGBoost** is that same student, but they have a high-speed library of textbooks, a perfectly organized workspace, and a strict rulebook (regularization) that prevents them from memorizing the textbook instead of understanding the concepts.

---

---
---

In [80]:
y[y=='No'] = 0
y[y=='Yes'] = 1

In [81]:
y

array([0, 0, 1, ..., 0, 1, 0], dtype=object)

In [83]:
# Splitting the data into training & test

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25)

# Converting data to integer
y_test = y_test.astype(int)
y_train = y_train.astype(int)

# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [84]:
# Call the XGB Classifier
from xgboost import XGBClassifier

# Initiating the classifier
model_xgb = XGBClassifier(n_estimators=100, max_depth=4,learning_rate=0.1)

# Passing the data to classifier
model_xgb.fit(X_train_sc, y_train)

# Predictions
y_pred_xgb = model_xgb.predict(X_test_sc)

In [85]:
print("Accuracy of XGB: ", accuracy_score(y_test, y_pred_xgb))

Accuracy of XGB:  0.8003412969283277