<a href="https://colab.research.google.com/github/KULDEEPSONI-source/MACHINE-LEARNING/blob/main/ML-SUPERVISEDLN-CLASSIFICATION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [17]:
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [19]:
df.TotalCharges = pd.to_numeric(df.TotalCharges, errors='coerce')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [21]:
df.dropna(how='any', inplace=True)

In [22]:
len(df)

7032

In [23]:
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [24]:
df.Churn.value_counts()/len(df)*100

Churn
No     73.421502
Yes    26.578498
Name: count, dtype: float64

In [25]:
X=df.drop(['customerID', 'Churn'], axis=1)

In [26]:
y=df.Churn.values

In [27]:
X

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50

In [28]:
y

array(['No', 'No', 'Yes', ..., 'No', 'Yes', 'No'], dtype=object)

In [29]:
X.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='object')

In [30]:
# Convert categorical features to numericals --> Feature Encoding --> Dummy Encoding

X = pd.get_dummies(X, columns=['gender', 'Partner', 'Dependents',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod'], drop_first=True)

In [31]:
X.head(1)

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,False,True,False,False,True,False,...,False,False,False,False,False,False,True,False,True,False

In [32]:
# Splitting the data into training & test

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25)

In [33]:
len(X_train)

5274

In [34]:
len(X_test)

1758

In [35]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [36]:
X_train_sc

array([[-0.43955963, -0.08744827, -1.50121024, ...,  1.9000368 ,
        -0.70740847, -0.55208659],
       [-0.43955963, -1.0267602 , -0.16904793, ..., -0.52630559,
        -0.70740847,  1.81131007],
       [-0.43955963, -0.04660862,  0.76446232, ..., -0.52630559,
         1.41361044, -0.55208659],
       ...,
       [-0.43955963,  0.11674998,  0.25451989, ..., -0.52630559,
         1.41361044, -0.55208659],
       [-0.43955963, -1.23095845,  0.37577656, ..., -0.52630559,
         1.41361044, -0.55208659],
       [-0.43955963, -1.2717981 , -0.6241757 , ..., -0.52630559,
         1.41361044, -0.55208659]])

In [37]:
X_test_sc

array([[-0.43955963,  1.627817  ,  0.82426013, ..., -0.52630559,
        -0.70740847,  1.81131007],
       [-0.43955963,  0.28010858,  1.38901723, ..., -0.52630559,
         1.41361044, -0.55208659],
       [-0.43955963, -0.74088266, -0.10592802, ..., -0.52630559,
        -0.70740847, -0.55208659],
       ...,
       [-0.43955963, -0.8634016 , -0.46637593, ..., -0.52630559,
         1.41361044, -0.55208659],
       [ 2.27500418, -0.12828792, -0.6507525 , ..., -0.52630559,
         1.41361044, -0.55208659],
       [-0.43955963, -1.2717981 ,  0.15984003, ..., -0.52630559,
        -0.70740847,  1.81131007]])

#### kNN Classifier

In [38]:
# Call the kNN Classifier
from sklearn.neighbors import KNeighborsClassifier

# Initiating the classifier
model = KNeighborsClassifier()

# Passing the data to classifier
model.fit(X_train_sc, y_train)

KNeighborsClassifier()

In [39]:
y_pred = model.predict(X_test_sc)

In [40]:
y_pred

array(['No', 'Yes', 'No', ..., 'No', 'Yes', 'Yes'], dtype=object)

In [41]:
y_test

array(['No', 'No', 'No', ..., 'No', 'No', 'Yes'], dtype=object)

In [42]:
# Classification metrics = to check how the model is behaving

from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred)*100)

76.16609783845279

#### New data prediction

In [43]:
X_test_sc

array([[-0.43955963,  1.627817  ,  0.82426013, ..., -0.52630559,
        -0.70740847,  1.81131007],
       [-0.43955963,  0.28010858,  1.38901723, ..., -0.52630559,
         1.41361044, -0.55208659],
       [-0.43955963, -0.74088266, -0.10592802, ..., -0.52630559,
        -0.70740847, -0.55208659],
       ...,
       [-0.43955963, -0.8634016 , -0.46637593, ..., -0.52630559,
         1.41361044, -0.55208659],
       [ 2.27500418, -0.12828792, -0.6507525 , ..., -0.52630559,
         1.41361044, -0.55208659],
       [-0.43955963, -1.2717981 ,  0.15984003, ..., -0.52630559,
        -0.70740847,  1.81131007]])

In [44]:
X_test.columns

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges',
       'gender_Male', 'Partner_Yes', 'Dependents_Yes', 'PhoneService_Yes',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_Fiber optic', 'InternetService_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No internet service', 'OnlineBackup_Yes',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No internet service', 'StreamingMovies_Yes',
       'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')

In [45]:
data = [[0, 2, 87, 178, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1]]

In [46]:
data_sc = sc.transform(data)

single = model.predict(data_sc)

print(single)

['Yes']

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [47]:
data_sc = sc.transform(data)

single = model.predict_proba(data_sc)

print(single)

[[0.4 0.6]]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

#### Decision Tree Classifier

In [48]:
# Call the DT Classifier
from sklearn.tree import DecisionTreeClassifier

# Initiating the classifier
model_dt = DecisionTreeClassifier()

# Passing the data to classifier
model_dt.fit(X_train_sc, y_train)

DecisionTreeClassifier()

In [49]:
y_pred_dt = model_dt.predict(X_test_sc)

In [50]:
# Classification metrics = to check how the model is behaving

from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred_dt)*100)

72.4118316268487

#### Random Forest Classifier

In [51]:
# Call the Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier

# Initiating the classifier
model_rf = RandomForestClassifier(n_estimators=200)

# Passing the data to classifier
model_rf.fit(X_train_sc, y_train)

RandomForestClassifier(n_estimators=200)

In [52]:
y_pred_rf = model_rf.predict(X_test_sc)

In [53]:
# Classification metrics = to check how the model is behaving

from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred_rf)*100)

78.839590443686

In [54]:
from sklearn.metrics import classification_report

knn_report = classification_report(y_test, y_pred)
dt_report = classification_report(y_test, y_pred_dt)
rf_report = classification_report(y_test, y_pred_rf)

In [55]:
print('knn report', knn_report)

knn report               precision    recall  f1-score   support

          No       0.83      0.85      0.84      1297
         Yes       0.55      0.52      0.53       461

    accuracy                           0.76      1758
   macro avg       0.69      0.68      0.69      1758
weighted avg       0.76      0.76      0.76      1758

In [56]:
print('dt report', dt_report)

dt report               precision    recall  f1-score   support

          No       0.81      0.82      0.81      1297
         Yes       0.47      0.46      0.47       461

    accuracy                           0.72      1758
   macro avg       0.64      0.64      0.64      1758
weighted avg       0.72      0.72      0.72      1758

In [57]:
print('rf report', rf_report)

rf report               precision    recall  f1-score   support

          No       0.83      0.90      0.86      1297
         Yes       0.63      0.46      0.54       461

    accuracy                           0.79      1758
   macro avg       0.73      0.68      0.70      1758
weighted avg       0.77      0.79      0.78      1758

#### Naive Bayes Classifier

In [58]:
# Call the Random Forest Classifier
from sklearn.naive_bayes import BernoulliNB

# Initiating the classifier
model_nb = BernoulliNB()

# Passing the data to classifier
model_nb.fit(X_train_sc, y_train)

# Predictions
y_pred_nb = model_nb.predict(X_test_sc)

# Accuracy Score
print(accuracy_score(y_test,y_pred_nb)*100)

73.43572241183163

#### SVM Classifier

In [59]:
# Call the Random Forest Classifier
from sklearn.svm import SVC

# Initiating the classifier
model_svc = SVC()

# Passing the data to classifier
model_svc.fit(X_train_sc, y_train)

# Predictions
y_pred_svc = model_svc.predict(X_test_sc)

# Accuracy Score
print(accuracy_score(y_test,y_pred_svc)*100)

79.63594994311718

In [60]:
svc_report = classification_report(y_test, y_pred_svc)
print(svc_report)

              precision    recall  f1-score   support

          No       0.83      0.90      0.87      1297
         Yes       0.65      0.49      0.56       461

    accuracy                           0.80      1758
   macro avg       0.74      0.70      0.71      1758
weighted avg       0.78      0.80      0.79      1758

#### Logistic Regression Classifier

In [61]:
# Call the Random Forest Classifier
from sklearn.linear_model import LogisticRegression

# Initiating the classifier
model_lr = LogisticRegression()

# Passing the data to classifier
model_lr.fit(X_train_sc, y_train)

# Predictions
y_pred_lr = model_lr.predict(X_test_sc)

# Accuracy Score
print(accuracy_score(y_test,y_pred_lr)*100)

80.3754266211604

In [62]:
lr_report = classification_report(y_test, y_pred_lr)
print(lr_report)

              precision    recall  f1-score   support

          No       0.85      0.90      0.87      1297
         Yes       0.65      0.54      0.59       461

    accuracy                           0.80      1758
   macro avg       0.75      0.72      0.73      1758
weighted avg       0.79      0.80      0.80      1758